global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:3000']
    metrics_path: '/metrics'

  - job_name: 'web-service'
    static_configs:
      - targets: ['web-service:3001']
    metrics_path: '/metrics' 