name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Prepare Database Package
      run: |
        cd packages/database
        npm install --production
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Terraform Init
      working-directory: ./infrastructure/environments/production
      run: |
        terraform init \
          -backend-config=backend.hcl
        
    - name: Terraform Plan
      working-directory: ./infrastructure/environments/production
      run: |
        terraform plan \
          -var="database_password=${{ secrets.DATABASE_PASSWORD }}" \
          -var="grafana_admin_password=${{ secrets.GRAFANA_ADMIN_PASSWORD }}" \
          -var="alert_email=${{ secrets.ALERT_EMAIL }}" \
          -out=tfplan
      
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ./infrastructure/environments/production
      run: terraform apply -auto-approve tfplan 