name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./infrastructure/environments/${{ vars.STAGE_NAME }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infrastructure/environments/${{ vars.STAGE_NAME }}
        run: |
          terraform plan \
            -var="environment=${{ vars.STAGE_NAME }}" \
            -var="database_password=${{ secrets.DATABASE_PASSWORD }}" \
            -var="grafana_admin_password=${{ secrets.GRAFANA_PASSWORD }}" \
            -var="alert_email=${{ secrets.ALERT_EMAIL }}" 