name: Trigger Database Migration

on:
  workflow_dispatch:  # Manual triggers only

jobs:
  trigger-migration:
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Trigger Lambda Function
        run: |
          aws lambda invoke \
            --function-name ${{ vars.STAGE_NAME }}-db-migrate \
            --payload '{}' \
            --log-type Tail \
            response.json | tee lambda-response.txt

          echo "Lambda Logs:"
          cat lambda-response.txt | jq -r '.LogResult' | base64 -d 